"""
SOAR Engine Orchestrator.

Listens for alerts and matches them to the appropriate playbook.
"""

import logging
from app.response.playbooks.block_ip import BlockIPPlaybook
from app.response.playbooks.disable_user import DisableUserPlaybook

logger = logging.getLogger("mini_soc.soar.engine")


class SoarEngine:
    def __init__(self):
        # Register available playbooks
        self.playbooks = [
            BlockIPPlaybook(),
            DisableUserPlaybook()
        ]
        
        # Build a mapping of rule_name -> list of playbooks to execute
        self.routing_table = {}
        for pb in self.playbooks:
            for alert_name in pb.target_alerts:
                if alert_name not in self.routing_table:
                    self.routing_table[alert_name] = []
                self.routing_table[alert_name].append(pb)
                
        logger.info(f"Initialized SOAR Engine with {len(self.playbooks)} playbooks.")

    def handle_alert(self, alert: dict):
        """
        Evaluate an alert and trigger appropriate playbooks.
        
        Args:
            alert: The alert dictionary generated by the DetectionEngine.
        """
        rule_name = alert.get("rule_name")
        if not rule_name:
            return
            
        # Severe alerts only
        severity = alert.get("severity", "low").lower()
        if severity not in ["high", "critical"]:
            return

        matching_playbooks = self.routing_table.get(rule_name, [])
        if not matching_playbooks:
            return
            
        logger.info(f"[SOAR] Processing high-severity '{rule_name}' alert...")
        
        for playbook in matching_playbooks:
            try:
                playbook.execute(alert)
            except Exception as e:
                logger.error(f"[SOAR] Playbook '{playbook.name}' failed: {e}")
